<a href="https://colab.research.google.com/github/vaishnavikondaparthy/MachineLearning/blob/main/2.4_Dealingwith_categorical_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("/content/Dataset_4(Salary).csv")

In [3]:
dataset.head(10)

     country   Salary  YearsExperience Purchased
0      Dubai  39343.0              1.1        No
1     Canada  46205.0              1.3       Yes
2     Canada  37731.0              1.5        No
3     Canada  43525.0              2.0        No
4        USA  39891.0              2.2        No
5      Dubai  56642.0              2.9        No
6     Canada  60150.0              3.0       Yes
7  Australia  54445.0              3.2        No
8      Dubai  64445.0              3.2       Yes
9      Dubai  57189.0              3.7        No

In [4]:
#applying one-hot encoding with python

In [5]:
country_dummy = pd.get_dummies(dataset['country'])

In [6]:
dataset = pd.concat([dataset, country_dummy],axis = 1)

In [7]:
dataset.drop('country',axis = 1, inplace = True)
dataset = dataset[['Australia', 'Canada','Dubai', 'USA','YearsExperience','Salary','Purchased']]

In [8]:
dataset

    Australia  Canada  Dubai  USA  YearsExperience    Salary Purchased
0           0       0      1    0              1.1   39343.0        No
1           0       1      0    0              1.3   46205.0       Yes
2           0       1      0    0              1.5   37731.0        No
3           0       1      0    0              2.0   43525.0        No
4           0       0      0    1              2.2   39891.0        No
5           0       0      1    0              2.9   56642.0        No
6           0       1      0    0              3.0   60150.0       Yes
7           1       0      0    0              3.2   54445.0        No
8           0       0      1    0              3.2   64445.0       Yes
9           0       0      1    0              3.7   57189.0        No
10          0       0      1    0              3.9   63218.0       Yes
11          0       0      0    1              4.0   55794.0        No
12          0       0      1    0              4.0   56957.0       Yes
13          0       1      0    0              4.1   57081.0        No
14          1       0      0    0              4.5   61111.0        No
15          0       0      0    1              4.9   67938.0        No
16          0       0      0    1              5.1   66029.0        No
17          0       1      0    0              5.3   83088.0        No
18          1       0      0    0              5.9   81363.0       Yes
19          0       1      0    0              6.0   93940.0        No
20          0       1      0    0              6.8   91738.0        No
21          1       0      0    0              7.1   98273.0        No
22          1       0      0    0              7.9  101302.0        No
23          1       0      0    0              8.2  113812.0       Yes
24          0       0      1    0              8.7  109431.0        No
25          1       0      0    0              9.0  105582.0       Yes
26          0       0      1    0              9.5  116969.0        No
27          0       0      0    1              9.6  112635.0       Yes
28          0       0      0    1             10.3  122391.0        No
29          0       1      0    0             10.5  121872.0       Yes

In [9]:
#applying one-hot encoding with scikit learn

In [10]:
# Lets first perform label encoding on price column because it has only two unique values 'Yes' and 'No'

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Purchased'] = le.fit_transform(dataset['Purchased'])

In [11]:
# Lets perform one-hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
df = pd.DataFrame(ct.fit_transform(dataset))

In [12]:
df.columns = ['','Australia','Canada','Dubai','USA','Salary', 'YearsExperience', 'Purchased']
df.head(10)

        Australia  Canada  Dubai  USA  Salary  YearsExperience  Purchased
0  1.0        0.0     0.0    1.0  0.0     1.1          39343.0        0.0
1  1.0        0.0     1.0    0.0  0.0     1.3          46205.0        1.0
2  1.0        0.0     1.0    0.0  0.0     1.5          37731.0        0.0
3  1.0        0.0     1.0    0.0  0.0     2.0          43525.0        0.0
4  1.0        0.0     0.0    0.0  1.0     2.2          39891.0        0.0
5  1.0        0.0     0.0    1.0  0.0     2.9          56642.0        0.0
6  1.0        0.0     1.0    0.0  0.0     3.0          60150.0        1.0
7  0.0        1.0     0.0    0.0  0.0     3.2          54445.0        0.0
8  1.0        0.0     0.0    1.0  0.0     3.2          64445.0        1.0
9  1.0        0.0     0.0    1.0  0.0     3.7          57189.0        0.0